# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: A:/FPGA/Vivado/A7/K9_F407/FPGA_Prj/mcu_fsmc_test/mcu_fsmc_test.srcs/sources_1/ip/ila_0/ila_0.xci
# IP: The module: 'ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: a:/FPGA/Vivado/A7/K9_F407/FPGA_Prj/mcu_fsmc_test/mcu_fsmc_test.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: a:/FPGA/Vivado/A7/K9_F407/FPGA_Prj/mcu_fsmc_test/mcu_fsmc_test.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: a:/FPGA/Vivado/A7/K9_F407/FPGA_Prj/mcu_fsmc_test/mcu_fsmc_test.gen/sources_1/ip/ila_0/ila_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: A:/FPGA/Vivado/A7/K9_F407/FPGA_Prj/mcu_fsmc_test/mcu_fsmc_test.srcs/sources_1/ip/ila_0/ila_0.xci
# IP: The module: 'ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: a:/FPGA/Vivado/A7/K9_F407/FPGA_Prj/mcu_fsmc_test/mcu_fsmc_test.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: a:/FPGA/Vivado/A7/K9_F407/FPGA_Prj/mcu_fsmc_test/mcu_fsmc_test.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: a:/FPGA/Vivado/A7/K9_F407/FPGA_Prj/mcu_fsmc_test/mcu_fsmc_test.gen/sources_1/ip/ila_0/ila_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
