# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: A:/FPGA/Vivado/A7/K9_F407/example/39_ov5640_rgb565_lcd/ov5640_rgb565_lcd.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: a:/FPGA/Vivado/A7/K9_F407/example/39_ov5640_rgb565_lcd/ov5640_rgb565_lcd.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: a:/FPGA/Vivado/A7/K9_F407/example/39_ov5640_rgb565_lcd/ov5640_rgb565_lcd.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: a:/FPGA/Vivado/A7/K9_F407/example/39_ov5640_rgb565_lcd/ov5640_rgb565_lcd.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: A:/FPGA/Vivado/A7/K9_F407/example/39_ov5640_rgb565_lcd/ov5640_rgb565_lcd.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: a:/FPGA/Vivado/A7/K9_F407/example/39_ov5640_rgb565_lcd/ov5640_rgb565_lcd.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: a:/FPGA/Vivado/A7/K9_F407/example/39_ov5640_rgb565_lcd/ov5640_rgb565_lcd.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: a:/FPGA/Vivado/A7/K9_F407/example/39_ov5640_rgb565_lcd/ov5640_rgb565_lcd.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
