#时钟复位
set_property PACKAGE_PIN W19 [get_ports sys_clk]
set_property PACKAGE_PIN Y19 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]

#AD信号
set_property PACKAGE_PIN L15 [get_ports ad_clk]
set_property PACKAGE_PIN N19 [get_ports {ad_data[7]}]
set_property PACKAGE_PIN N18 [get_ports {ad_data[6]}]
set_property PACKAGE_PIN L18 [get_ports {ad_data[5]}]
set_property PACKAGE_PIN M18 [get_ports {ad_data[4]}]
set_property PACKAGE_PIN L20 [get_ports {ad_data[3]}]
set_property PACKAGE_PIN L19 [get_ports {ad_data[2]}]
set_property PACKAGE_PIN L21 [get_ports {ad_data[1]}]
set_property PACKAGE_PIN M21 [get_ports {ad_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ad_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data[0]}]

#数码管信号
set_property PACKAGE_PIN K18 [get_ports {sel[5]}]
set_property PACKAGE_PIN K16 [get_ports {sel[4]}]
set_property PACKAGE_PIN L16 [get_ports {sel[3]}]
set_property PACKAGE_PIN G20 [get_ports {sel[2]}]
set_property PACKAGE_PIN H20 [get_ports {sel[1]}]
set_property PACKAGE_PIN H18 [get_ports {sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[0]}]

set_property PACKAGE_PIN U22 [get_ports {seg[0]}]
set_property PACKAGE_PIN P19 [get_ports {seg[1]}]
set_property PACKAGE_PIN W21 [get_ports {seg[2]}]
set_property PACKAGE_PIN V22 [get_ports {seg[3]}]
set_property PACKAGE_PIN AB20 [get_ports {seg[4]}]
set_property PACKAGE_PIN W22 [get_ports {seg[5]}]
set_property PACKAGE_PIN AA20 [get_ports {seg[6]}]
set_property PACKAGE_PIN AA21 [get_ports {seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]

set_property PACKAGE_PIN P15 [get_ports key_mode]
set_property PACKAGE_PIN R16 [get_ports key_start]
set_property IOSTANDARD LVCMOS33 [get_ports key_mode]
set_property IOSTANDARD LVCMOS33 [get_ports key_start]

set_property PACKAGE_PIN R16 [get_ports key_cal]
set_property IOSTANDARD LVCMOS33 [get_ports key_cal]

set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_tft[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports tft_bl]
set_property IOSTANDARD LVCMOS33 [get_ports tft_clk]
set_property IOSTANDARD LVCMOS33 [get_ports tft_de]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]

set_property PACKAGE_PIN W19 [get_ports sys_clk]
set_property PACKAGE_PIN Y19 [get_ports sys_rst_n]

set_property PACKAGE_PIN E19 [get_ports hsync]
set_property PACKAGE_PIN AA19 [get_ports tft_bl]
set_property PACKAGE_PIN D19 [get_ports tft_clk]
set_property PACKAGE_PIN B17 [get_ports tft_de]
set_property PACKAGE_PIN B18 [get_ports vsync]
set_property PACKAGE_PIN J20 [get_ports {rgb_tft[15]}]
set_property PACKAGE_PIN J21 [get_ports {rgb_tft[14]}]
set_property PACKAGE_PIN K13 [get_ports {rgb_tft[13]}]
set_property PACKAGE_PIN K14 [get_ports {rgb_tft[12]}]
set_property PACKAGE_PIN K17 [get_ports {rgb_tft[11]}]
set_property PACKAGE_PIN H13 [get_ports {rgb_tft[10]}]
set_property PACKAGE_PIN G13 [get_ports {rgb_tft[9]}]
set_property PACKAGE_PIN G17 [get_ports {rgb_tft[8]}]
set_property PACKAGE_PIN G18 [get_ports {rgb_tft[7]}]
set_property PACKAGE_PIN J15 [get_ports {rgb_tft[6]}]
set_property PACKAGE_PIN H15 [get_ports {rgb_tft[5]}]
set_property PACKAGE_PIN D20 [get_ports {rgb_tft[4]}]
set_property PACKAGE_PIN C20 [get_ports {rgb_tft[3]}]
set_property PACKAGE_PIN A18 [get_ports {rgb_tft[2]}]
set_property PACKAGE_PIN A19 [get_ports {rgb_tft[1]}]
set_property PACKAGE_PIN C22 [get_ports {rgb_tft[0]}]


