
set_property IOSTANDARD LVCMOS33 [get_ports {sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[0]}]
set_property PACKAGE_PIN K19 [get_ports sys_rst_n]
set_property PACKAGE_PIN H14 [get_ports {sel[0]}]
set_property PACKAGE_PIN H15 [get_ports {sel[1]}]
set_property PACKAGE_PIN G15 [get_ports {sel[2]}]
set_property PACKAGE_PIN G16 [get_ports {sel[3]}]

set_property PACKAGE_PIN G17 [get_ports {seg_led[0]}]
set_property PACKAGE_PIN H17 [get_ports {seg_led[1]}]
set_property PACKAGE_PIN H18 [get_ports {seg_led[2]}]
set_property PACKAGE_PIN H19 [get_ports {seg_led[3]}]
set_property PACKAGE_PIN G20 [get_ports {seg_led[4]}]
set_property PACKAGE_PIN J16 [get_ports {seg_led[5]}]
set_property PACKAGE_PIN J15 [get_ports {seg_led[6]}]
set_property PACKAGE_PIN K16 [get_ports {seg_led[7]}]
